### ISSUE TITLE
Order of posts across timezones

### ISSUE THREAD

**Issue by elapse2039** [havenweb/haven#106]
I cant quite determine what is going on but some posts by some users end up not being displayed in chronological order.

Today there are five posts, 4 from User A and 1 from user B.

User B wrote their post last by a few hours... but it is presented in between post 2&3 from user A.

I have not spotted any pattern yet with usernames, names, comments or likes influencing this ordering.

I was surprised to see this latest post at number 3 out of 5 (top to bottom of blog page) given it was written last.

Also I see posts are paginated... what determines a new page on the site?

**Comment by mawise** [comment]
Hmm... there are a couple things that might be going on:

   - Currently, posts get their timestamp when the author clicks the 'new
   post' button, not when they click the 'save post' button.  If you have a
   browser tab open for a few hours or days as you're working on a post, that
   post may get posted as an older post.
   - Also, I think I've been sloppy with timezones.  If different people
   are in different timezones, it may be naïvely comparing and ordering by
   local time for each author instead of properly converting to UTC for
   comparison.


Pagination is based on the number of posts, it doesn't matter how long each
post is.

**Comment by elapse2039** [comment]
Yes, timezones! One device is in EST and the other GMT. That explains the order.
