### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by potter-jason** [havenweb/haven#76]
hi

im getting the following when running the docker compose file

=> ERROR [haven  7/13] RUN APT update                                                         0.4s
------
 > [haven  7/13] RUN APT update:
0.345 /bin/sh: 1: APT: not found
------
failed to solve: process "/bin/sh -c APT update" did not complete successfully: exit code: 127

This is after 2-3 minutes of building, then this error and stops.

Is this a known issues or something someone as seen before? Thanks!

**Comment by mawise** [comment]
Hi @potter-jason , that is not expected.  I just ran `docker-compose up` on my machine against the latest master branch with no issues.  Can you share more information about your setup?  Are you modifying the `docker-compose.yml` or `Dockerfile` files at all?  Anything else that might be useful?

The `Dockerfile` calls `apt-get update` instead of `apt update` which seems curious looking at your error message.

**Comment by mawise** [comment]
Hi @potter-jason , I'm closing this issue, but feel free to reach out if you have other details that might help in debugging.
