### ISSUE TITLE
docker-compose setup - css and other style changes do not take effect

### ISSUE THREAD

**Issue by elapse2039** [havenweb/haven#91]
Thanks for this great OSS project... I've got it working in a docker-compose file (see attached example) and trying to customise the font and CSS layout as per the help docs the project sends me to.  Nothing seems to happen... even restarting the service makes no difference.

[docker-comp.txt](https://github.com/user-attachments/files/15526705/docker-comp.txt)

Is there another docker volume I should mount locally for these changes to persist?
This is while using Firefox browser.

Thx.

**Comment by elapse2039** [comment]
Ok, the fonts now take effect... not sure why there weren't earlier... the only thing I haven't got working yet is to force the dark/light theme.

**Comment by mawise** [comment]
If you can figure out a way to reproduce the font issue, I would love to fix it.  I'm glad to hear it's working now but I don't think the inconsistent behavior is satisfactory.

For dark/light, you can set the same colors in the `:root` section as the `@media screen and (prefers-color-scheme: dark)` section, or create a new `@media screen` section so that printing a page still uses the light colors.  Alternately, you can modify the css in the Haven source code here: https://github.com/havenweb/haven/tree/master/app/assets/stylesheets

**Comment by elapse2039** [comment]
I think this was due to my misunderstanding of css example. I cant find a problem with this after reading the help guide more closely.
